apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fl-front-deploy
  name: fl-front-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: fl-front-deploy
status:
  loadBalancer: {}
